name: 'Setup Node.js Environment'
description: 'Sets up Node.js and installs dependencies'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20.x'
  cache:
    description: 'Cache to use (npm/yarn)'
    required: false
    default: 'npm'
  clean-install:
    description: 'Whether to clean install dependencies'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}

    - name: Install dependencies
      shell: bash
      run: |
        if [ "${{ inputs.clean-install }}" = "true" ]; then
          rm -rf node_modules package-lock.json
          npm install
        else
          npm ci
        fi

    - name: Build
      shell: bash
      run: npm run build